# Optimización de Modelos Conjunto Soleado por GMM

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('/content/drive/MyDrive/Tesina/03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso


In [3]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [4]:
datos_dia = datos[datos["Cluster GMM"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
36,2022-09-02 12:00:00,27523.885172,21,57,4,12,Nublado,Nublado,17036.043251,29196.986647
37,2022-09-02 13:00:00,20596.278869,23,45,5,13,Nublado,Nublado,27523.885172,25478.471342
38,2022-09-02 14:00:00,28500.000000,24,37,6,14,Nublado,Nublado,20596.278869,29057.585772
39,2022-09-02 15:00:00,24647.568577,26,33,5,15,Nublado,Nublado,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,34,4,16,Nublado,Nublado,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,36,2,17,Nublado,Nublado,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,39,1,18,Nublado,Nublado,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,44,1,19,Nublado,Nublado,22733.515002,18282.505369
61,2022-09-03 13:00:00,20400.000000,23,48,5,13,Nublado,Nublado,17723.695569,20596.278869
65,2022-09-03 17:00:00,25602.778606,25,45,5,17,Nublado,Nublado,23122.803757,24281.956494


In [5]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [6]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,21,57,4,12,17036.043251,29196.986647
37,23,45,5,13,27523.885172,25478.471342
38,24,37,6,14,20596.278869,29057.585772
39,26,33,5,15,28500.000000,30000.000000
40,27,34,4,16,24647.568577,28062.328964
...,...,...,...,...,...,...
18281,26,31,4,16,25562.000000,25385.000000
18282,26,32,2,17,25386.000000,22664.000000
18283,25,33,1,18,22872.000000,15736.000000
18284,23,38,0,19,15825.000000,1407.000000


In [7]:
y = datos_dia[['Generación']]
y

,Generación
36,27523.885172
37,20596.278869
38,28500.000000
39,24647.568577
40,25500.000000
...,...
18281,25386.000000
18282,22872.000000
18283,15825.000000
18284,1450.000000


Dividimos entrenamiento, validación y prueba

In [8]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [9]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 3252, y_train: 3252
X_val: 697, y_val: 697
X_test: 697, y_test: 697


## Escalar con MinMaxScaler

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [12]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.43333333 0.98113208 0.4        0.4        0.56786811 0.97323289]
 [0.5        0.75471698 0.5        0.46666667 0.91746284 0.84928238]
 [0.53333333 0.60377358 0.6        0.53333333 0.68654263 0.96858619]
 ...
 [0.4        0.67924528 0.         1.         0.         0.        ]
 [0.26666667 0.81132075 0.4        0.33333333 0.6396     0.67536667]
 [0.4        0.56603774 0.5        0.4        0.66776667 0.65666667]]
(3252, 6)


In [13]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.433333,0.981132,0.4,0.400000,0.567868,0.973233
37,0.500000,0.754717,0.5,0.466667,0.917463,0.849282
38,0.533333,0.603774,0.6,0.533333,0.686543,0.968586
39,0.600000,0.528302,0.5,0.600000,0.950000,1.000000
40,0.633333,0.547170,0.4,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
12596,0.633333,0.226415,0.0,0.866667,0.319667,0.173900
12597,0.500000,0.396226,0.0,0.933333,0.026400,0.000000
12598,0.400000,0.679245,0.0,1.000000,0.000000,0.000000
12612,0.266667,0.811321,0.4,0.333333,0.639600,0.675367


In [14]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.5        0.39622642 0.6        0.46666667 0.65776667 0.71383333]
 [0.56666667 0.30188679 0.5        0.53333333 0.63403333 0.62716667]
 [0.63333333 0.22641509 0.4        0.6        0.63616667 0.62633333]
 ...
 [0.4        0.49056604 0.3        0.2        0.37583333 0.7706    ]
 [0.53333333 0.30188679 0.5        0.26666667 0.74553333 0.859     ]
 [0.9        0.05660377 0.7        0.6        0.84236667 0.94003333]]
(697, 6)


In [15]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
12614,0.500000,0.396226,0.6,0.466667,0.657767,0.713833
12615,0.566667,0.301887,0.5,0.533333,0.634033,0.627167
12616,0.633333,0.226415,0.4,0.600000,0.636167,0.626333
12617,0.666667,0.150943,0.3,0.666667,0.655400,0.626067
12618,0.733333,0.113208,0.2,0.733333,0.737567,0.527167
...,...,...,...,...,...,...
14590,0.633333,0.490566,0.0,1.000000,0.009467,0.000000
14601,0.300000,0.716981,0.2,0.133333,0.044967,0.422800
14602,0.400000,0.490566,0.3,0.200000,0.375833,0.770600
14603,0.533333,0.301887,0.5,0.266667,0.745533,0.859000


In [16]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.93333333 0.03773585 0.2        0.66666667 0.83383333 0.91813333]
 [0.96666667 0.03773585 0.2        0.73333333 0.72056667 0.88203333]
 [0.93333333 0.03773585 0.1        0.8        0.67996667 0.7186    ]
 ...
 [0.56666667 0.52830189 0.1        0.8        0.7624     0.52453333]
 [0.5        0.62264151 0.         0.86666667 0.5275     0.0469    ]
 [0.46666667 0.75471698 0.         0.93333333 0.04833333 0.        ]]
(697, 6)


In [17]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
14609,0.933333,0.037736,0.2,0.666667,0.833833,0.918133
14610,0.966667,0.037736,0.2,0.733333,0.720567,0.882033
14611,0.933333,0.037736,0.1,0.800000,0.679967,0.718600
14612,0.900000,0.037736,0.0,0.866667,0.574900,0.273700
14613,0.800000,0.075472,0.0,0.933333,0.218967,0.009467
...,...,...,...,...,...,...
18281,0.600000,0.490566,0.4,0.666667,0.852067,0.846167
18282,0.600000,0.509434,0.2,0.733333,0.846200,0.755467
18283,0.566667,0.528302,0.1,0.800000,0.762400,0.524533
18284,0.500000,0.622642,0.0,0.866667,0.527500,0.046900


In [18]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()


In [19]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.41935484 0.94736842 0.4        0.4        0.56786811 0.97323289]
 [0.48387097 0.73684211 0.5        0.46666667 0.91746284 0.84928238]
 [0.51612903 0.59649123 0.6        0.53333333 0.68654263 0.96858619]
 ...
 [0.5483871  0.52631579 0.1        0.8        0.7624     0.52453333]
 [0.48387097 0.61403509 0.         0.86666667 0.5275     0.0469    ]
 [0.4516129  0.73684211 0.         0.93333333 0.04833333 0.        ]]
(4646, 6)


In [20]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.419355,0.947368,0.4,0.400000,0.567868,0.973233
37,0.483871,0.736842,0.5,0.466667,0.917463,0.849282
38,0.516129,0.596491,0.6,0.533333,0.686543,0.968586
39,0.580645,0.526316,0.5,0.600000,0.950000,1.000000
40,0.612903,0.543860,0.4,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
18281,0.580645,0.491228,0.4,0.666667,0.852067,0.846167
18282,0.580645,0.508772,0.2,0.733333,0.846200,0.755467
18283,0.548387,0.526316,0.1,0.800000,0.762400,0.524533
18284,0.483871,0.614035,0.0,0.866667,0.527500,0.046900


In [21]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()


In [22]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.        ]
 [0.66776667]
 [0.65776667]]
(3252, 1)


In [23]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

,Generación
36,0.917463
37,0.686543
38,0.950000
39,0.821586
40,0.850000
...,...
12596,0.026400
12597,0.000000
12598,0.000000
12612,0.667767


In [24]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[6.34033333e-01]
 [6.36166667e-01]
 [6.55400000e-01]
 [7.37566667e-01]
 [5.70933333e-01]
 [3.33533333e-01]
 [2.61000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.70400000e-01]
 [6.63633333e-01]
 [6.37766667e-01]
 [6.27166667e-01]
 [6.26333333e-01]
 [6.40166667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.65333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.34700000e-01]
 [8.30300000e-01]
 [7.99833333e-01]
 [7.87100000e-01]
 [7.82933333e-01]
 [8.26866667e-01]
 [7.83933333e-01]
 [4.66100000e-01]
 [4.78000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.34700000e-01]
 [8.40866667e-01]
 [8.04600000e-01]
 [7.83966667e-01]
 [7.82933333e-01]
 [8.25166667e-01]
 [7.76633333e-01]
 [4.66033333e-01]
 [6.56666667e-01]
 [6.38400000e-01]
 [6.27833333e-01]
 [6.29333333e-01]
 [6.26066667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.47666667e-02]
 [6.34033333e-01]
 [6.27166667e-01]
 [6.33666667e-01]
 [6.26066667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.28833333e-01]
 [3.33833333e-01]
 [3.163000

In [25]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

,Generación
12614,0.634033
12615,0.636167
12616,0.655400
12617,0.737567
12618,0.570933
...,...
14590,0.000000
14601,0.375833
14602,0.745533
14603,0.742033


In [26]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.72056667]
 [0.67996667]
 [0.5749    ]
 [0.21896667]
 [0.00756667]
 [0.        ]
 [0.81536667]
 [0.90996667]
 [0.80986667]
 [0.76953333]
 [0.5749    ]
 [0.22023333]
 [0.0078    ]
 [0.        ]
 [0.81026667]
 [0.76496667]
 [0.7186    ]
 [0.2851    ]
 [0.0097    ]
 [0.        ]
 [0.80986667]
 [0.8513    ]
 [0.7186    ]
 [0.2862    ]
 [0.01033333]
 [0.        ]
 [0.83926667]
 [0.72      ]
 [0.68456667]
 [0.5749    ]
 [0.2982    ]
 [0.0105    ]
 [0.        ]
 [0.        ]
 [0.05056667]
 [0.39346667]
 [0.6523    ]
 [0.72796667]
 [0.74653333]
 [0.75363333]
 [0.7465    ]
 [0.7461    ]
 [0.7414    ]
 [0.72333333]
 [0.6804    ]
 [0.57563333]
 [0.22806667]
 [0.00756667]
 [0.        ]
 [0.57076667]
 [0.71923333]
 [0.74653333]
 [0.66036667]
 [0.65023333]
 [0.7461    ]
 [0.74116667]
 [0.6299    ]
 [0.59496667]
 [0.58286667]
 [0.22686667]
 [0.00763333]
 [0.        ]
 [0.4228    ]
 [0.6523    ]
 [0.8983    ]
 [0.6337    ]
 [0.51133333]
 [0.64676667]
 [0.24633333]
 [0.00973333]
 [0.        ]
 [0.81

In [27]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

,Generación
14609,0.720567
14610,0.679967
14611,0.574900
14612,0.218967
14613,0.007567
...,...
18281,0.846200
18282,0.762400
18283,0.527500
18284,0.048333


In [28]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()


In [29]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(4646, 1)


In [30]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

,Generación
36,0.917463
37,0.686543
38,0.950000
39,0.821586
40,0.850000
...,...
18281,0.846200
18282,0.762400
18283,0.527500
18284,0.048333


## Preparación para Redes Neuronales

In [31]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []

    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada

        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df


In [32]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)


In [33]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (3204, 48, 6), y_train: (3204, 1)
X_val: (649, 48, 6), y_val: (649, 1)
X_test: (649, 48, 6), y_test: (649, 1)


## Optuna

In [34]:
pip install optuna

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.8/231.8 kB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 6.7 MB/s eta 0:00:00


In [35]:
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

### Optimización de LightGBM

In [36]:
import optuna
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error

# Definir la función de optimización
def objective(trial):
    # Espacio de búsqueda para los hiperparámetros
    num_leaves = trial.suggest_int('num_leaves', 10, 1000)
    subsample = trial.suggest_float('subsample', 0.1, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.1, 1.0)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 10, 100)

    # Modelo LightGBM con los hiperparámetros sugeridos
    model = LGBMRegressor(
        num_leaves=num_leaves,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        min_data_in_leaf=min_data_in_leaf,
        random_state=42
    )

    # Entrenamos el modelo con los datos de entrenamiento
    model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Ejecutar la optimización con 50 iteraciones
LightGBM_study = optuna.create_study(direction="minimize")
LightGBM_study.optimize(objective, n_trials=50)

# Obtener los mejores hiperparámetros
best_params = LightGBM_study.best_params
print("Mejores hiperparámetros:", best_params)

[I 2025-03-14 15:12:54,449] A new study created in memory with name: no-name-3f03476b-33c6-42b3-a776-e237ebf80e3a
[I 2025-03-14 15:12:54,611] Trial 0 finished with value: 0.003783536093271137 and parameters: {'num_leaves': 330, 'subsample': 0.37006545246357303, 'colsample_bytree': 0.477989637553906, 'min_data_in_leaf': 52}. Best is trial 0 with value: 0.003783536093271137.


[LightGBM] [Warning] min_data_in_leaf is set=52, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=52
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=52, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=52
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000888 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with posi

[I 2025-03-14 15:12:54,731] Trial 1 finished with value: 0.0038497716377749475 and parameters: {'num_leaves': 253, 'subsample': 0.3754725026664192, 'colsample_bytree': 0.6822636566845305, 'min_data_in_leaf': 40}. Best is trial 0 with value: 0.003783536093271137.
[I 2025-03-14 15:12:54,820] Trial 2 finished with value: 0.0036074113184906957 and parameters: {'num_leaves': 984, 'subsample': 0.4594018619072756, 'colsample_bytree': 0.6629039540838805, 'min_data_in_leaf': 70}. Best is trial 2 with value: 0.0036074113184906957.
[I 2025-03-14 15:12:54,864] Trial 3 finished with value: 0.0046011157374755566 and parameters: {'num_leaves': 82, 'subsample': 0.8742152130842845, 'colsample_bytree': 0.3544013449597859, 'min_data_in_leaf': 100}. Best is trial 2 with value: 0.0036074113184906957.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:54,939] Trial 4 finished with value: 0.0035740050955572387 and parameters: {'num_leaves': 799, 'subsample': 0.819336887221671, 'colsample_bytree': 0.645452583570322, 'min_data_in_leaf': 67}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:55,014] Trial 5 finished with value: 0.0036719742326083633 and parameters: {'num_leaves': 609, 'subsample': 0.9076060474976164, 'colsample_bytree': 0.727627179003159, 'min_data_in_leaf': 58}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:55,140] Trial 6 finished with value: 0.004113100884095724 and parameters: {'num_leaves': 821, 'subsample': 0.3252005012615507, 'colsample_bytree': 0.5421981590162397, 'min_data_in_leaf': 32}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:55,196] Trial 7 finished with value: 0.004769534781351315 and parameters: {'num_leaves': 506, 'subsample': 0.24770799858183337, 'colsample_bytree': 0.2382777137301487, 'min_data_in_leaf': 94}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:55,273] Trial 8 finished with value: 0.00464857830178893 and parameters: {'num_leaves': 378, 'subsample': 0.6756919981990112, 'colsample_bytree': 0.11632162024595182, 'min_data_in_leaf': 38}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:55,336] Trial 9 finished with value: 0.003950011019465389 and parameters: {'num_leaves': 89, 'subsample': 0.8516411494719114, 'colsample_bytree': 0.8647693482028067, 'min_data_in_leaf': 79}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=79, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=79
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000260 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

[I 2025-03-14 15:12:55,589] Trial 10 finished with value: 0.004700255344369418 and parameters: {'num_leaves': 724, 'subsample': 0.6516790037909073, 'colsample_bytree': 0.9789629659040222, 'min_data_in_leaf': 17}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:55,678] Trial 11 finished with value: 0.0036821084006106257 and parameters: {'num_leaves': 990, 'subsample': 0.5446982827625737, 'colsample_bytree': 0.7160926342860985, 'min_data_in_leaf': 74}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:55,773] Trial 12 finished with value: 0.003606201017055559 and parameters: {'num_leaves': 974, 'subsample': 0.5194625731080839, 'colsample_bytree': 0.615351734817413, 'min_data_in_leaf': 68}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:55,878] Trial 13 finished with value: 0.0038515362578694676 and parameters: {'num_leaves': 806, 'subsample': 0.10733642353399125, 'colsample_bytree': 0.4290262078704735, 'min_data_in_leaf': 56}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000201 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further split

[I 2025-03-14 15:12:55,969] Trial 14 finished with value: 0.0037977765453062495 and parameters: {'num_leaves': 868, 'subsample': 0.7087673777926635, 'colsample_bytree': 0.8401566107776567, 'min_data_in_leaf': 84}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:56,067] Trial 15 finished with value: 0.0035740050955572387 and parameters: {'num_leaves': 668, 'subsample': 0.7611537944800489, 'colsample_bytree': 0.6002476417697284, 'min_data_in_leaf': 67}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=84, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=84
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000152 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

[I 2025-03-14 15:12:56,175] Trial 16 finished with value: 0.003682291468169195 and parameters: {'num_leaves': 642, 'subsample': 0.7796758417456465, 'colsample_bytree': 0.81458088243742, 'min_data_in_leaf': 62}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:56,267] Trial 17 finished with value: 0.003918188551952615 and parameters: {'num_leaves': 550, 'subsample': 0.984012207983055, 'colsample_bytree': 0.5465567654042969, 'min_data_in_leaf': 86}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:56,381] Trial 18 finished with value: 0.0046328890832314645 and parameters: {'num_leaves': 712, 'subsample': 0.7604859549204466, 'colsample_bytree': 0.3503746837067022, 'min_data_in_leaf': 45}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:56,780] Trial 19 finished with value: 0.004617396656789978 and parameters: {'num_leaves': 422, 'subsample': 0.6399669289787477, 'colsample_bytree': 0.975304547627821, 'min_data_in_leaf': 10}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=10, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=10
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000118 seconds.


[I 2025-03-14 15:12:56,931] Trial 20 finished with value: 0.004077418916392317 and parameters: {'num_leaves': 680, 'subsample': 0.9683907472706101, 'colsample_bytree': 0.593793656159555, 'min_data_in_leaf': 30}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:57,027] Trial 21 finished with value: 0.003606201017055559 and parameters: {'num_leaves': 896, 'subsample': 0.5656371752066176, 'colsample_bytree': 0.6142310186773728, 'min_data_in_leaf': 68}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=30, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=30
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=68, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=68
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000119 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score

[I 2025-03-14 15:12:57,129] Trial 22 finished with value: 0.003819363344985942 and parameters: {'num_leaves': 767, 'subsample': 0.5583066508560067, 'colsample_bytree': 0.4640702667148899, 'min_data_in_leaf': 65}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:57,253] Trial 23 finished with value: 0.0038078731283860915 and parameters: {'num_leaves': 915, 'subsample': 0.7887933783305342, 'colsample_bytree': 0.7609704016192972, 'min_data_in_leaf': 50}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=65, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=65
[LightGBM] [Warning] min_data_in_leaf is set=50, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=50
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=50, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=50
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000125 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best g

[I 2025-03-14 15:12:57,348] Trial 24 finished with value: 0.00359990768672784 and parameters: {'num_leaves': 929, 'subsample': 0.46838238163365353, 'colsample_bytree': 0.6228600206546743, 'min_data_in_leaf': 77}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:57,454] Trial 25 finished with value: 0.004012977621172927 and parameters: {'num_leaves': 797, 'subsample': 0.8490742380044137, 'colsample_bytree': 0.5181988015313619, 'min_data_in_leaf': 80}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:57,537] Trial 26 finished with value: 0.004534598823066737 and parameters: {'num_leaves': 603, 'subsample': 0.4626454471010493, 'colsample_bytree': 0.38464821784317393, 'min_data_in_leaf': 76}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:57,621] Trial 27 finished with value: 0.0037373017131109255 and parameters: {'num_leaves': 897, 'subsample': 0.6038617440933131, 'colsample_bytree': 0.7820250674595371, 'min_data_in_leaf': 90}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:57,723] Trial 28 finished with value: 0.003610018774601715 and parameters: {'num_leaves': 749, 'subsample': 0.7192121651801298, 'colsample_bytree': 0.6268478889136837, 'min_data_in_leaf': 61}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:57,845] Trial 29 finished with value: 0.003848355188864726 and parameters: {'num_leaves': 551, 'subsample': 0.4375937616370513, 'colsample_bytree': 0.49145502891287585, 'min_data_in_leaf': 49}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] min_data_in_leaf is set=49, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=49
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=49, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=49
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further split

[I 2025-03-14 15:12:57,954] Trial 30 finished with value: 0.0038192494858084935 and parameters: {'num_leaves': 251, 'subsample': 0.9351065493221014, 'colsample_bytree': 0.9146323155408829, 'min_data_in_leaf': 73}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:58,051] Trial 31 finished with value: 0.00365439256778846 and parameters: {'num_leaves': 938, 'subsample': 0.5306457701686236, 'colsample_bytree': 0.5886046476147757, 'min_data_in_leaf': 66}. Best is trial 4 with value: 0.0035740050955572387.
[I 2025-03-14 15:12:58,137] Trial 32 finished with value: 0.0036715451812160014 and parameters: {'num_leaves': 871, 'subsample': 0.3764316845952516, 'colsample_bytree': 0.6622096176021751, 'min_data_in_leaf': 82}. Best is trial 4 with value: 0.0035740050955572387.


[LightGBM] [Warning] min_data_in_leaf is set=73, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=73
[LightGBM] [Warning] min_data_in_leaf is set=66, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=66
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=66, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=66
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best g

[I 2025-03-14 15:12:58,238] Trial 33 finished with value: 0.0035648600275307203 and parameters: {'num_leaves': 990, 'subsample': 0.4913932898599116, 'colsample_bytree': 0.6988987393109299, 'min_data_in_leaf': 71}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:58,336] Trial 34 finished with value: 0.0035648600275307203 and parameters: {'num_leaves': 847, 'subsample': 0.41227355843797164, 'colsample_bytree': 0.6691253779952269, 'min_data_in_leaf': 71}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] min_data_in_leaf is set=71, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=71
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=71, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=71
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further split

[I 2025-03-14 15:12:58,453] Trial 35 finished with value: 0.003697716231546361 and parameters: {'num_leaves': 838, 'subsample': 0.31609181123105, 'colsample_bytree': 0.6861639760934363, 'min_data_in_leaf': 54}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:58,549] Trial 36 finished with value: 0.0035648600275307203 and parameters: {'num_leaves': 675, 'subsample': 0.2322305519552289, 'colsample_bytree': 0.7427506877913076, 'min_data_in_leaf': 71}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=54, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=54
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000135 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

[I 2025-03-14 15:12:58,656] Trial 37 finished with value: 0.003655359824503627 and parameters: {'num_leaves': 783, 'subsample': 0.19472943563631484, 'colsample_bytree': 0.7518504748339122, 'min_data_in_leaf': 59}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:58,761] Trial 38 finished with value: 0.003620106292214945 and parameters: {'num_leaves': 996, 'subsample': 0.23744877975578982, 'colsample_bytree': 0.6983489768869278, 'min_data_in_leaf': 72}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] min_data_in_leaf is set=59, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=59
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=59, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=59
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000188 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further split

[I 2025-03-14 15:12:58,847] Trial 39 finished with value: 0.003793936529641922 and parameters: {'num_leaves': 703, 'subsample': 0.3854735652245091, 'colsample_bytree': 0.8897526825207945, 'min_data_in_leaf': 100}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:58,954] Trial 40 finished with value: 0.0037077018484473973 and parameters: {'num_leaves': 844, 'subsample': 0.31689493991203216, 'colsample_bytree': 0.8017529396355301, 'min_data_in_leaf': 63}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000133 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further s

[I 2025-03-14 15:12:59,051] Trial 41 finished with value: 0.003620106292214945 and parameters: {'num_leaves': 655, 'subsample': 0.15057903122460525, 'colsample_bytree': 0.7383402181291197, 'min_data_in_leaf': 72}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:59,132] Trial 42 finished with value: 0.003594016134889769 and parameters: {'num_leaves': 454, 'subsample': 0.26848898764449425, 'colsample_bytree': 0.6701437526712223, 'min_data_in_leaf': 90}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:59,233] Trial 43 finished with value: 0.003582177286061958 and parameters: {'num_leaves': 726, 'subsample': 0.4094379643597075, 'colsample_bytree': 0.6516872301268656, 'min_data_in_leaf': 69}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:59,337] Trial 44 finished with value: 0.00388626869925915 and parameters: {'num_leaves': 610, 'subsample': 0.48808953196339283, 'colsample_bytree': 0.5605032116428638, 'min_data_in_leaf': 57}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:59,439] Trial 45 finished with value: 0.00359990768672784 and parameters: {'num_leaves': 953, 'subsample': 0.8183849747494373, 'colsample_bytree': 0.7107177040586123, 'min_data_in_leaf': 77}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:59,526] Trial 46 finished with value: 0.00392691920550046 and parameters: {'num_leaves': 559, 'subsample': 0.6048130238526697, 'colsample_bytree': 0.5729212941884466, 'min_data_in_leaf': 87}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:59,640] Trial 47 finished with value: 0.0037515433965059934 and parameters: {'num_leaves': 823, 'subsample': 0.8972897453151496, 'colsample_bytree': 0.8344627083336553, 'min_data_in_leaf': 65}. Best is trial 33 with value: 0.0035648600275307203.
[I 2025-03-14 15:12:59,742] Trial 48 finished with value: 0.0037931241874296535 and parameters: {'num_leaves': 666, 'subsample': 0.3438561411576009, 'colsample_bytree': 0.5186881218719719, 'min_data_in_leaf': 71}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-03-14 15:12:59,834] Trial 49 finished with value: 0.0037358939946032063 and parameters: {'num_leaves': 34, 'subsample': 0.4284004242004754, 'colsample_bytree': 0.723741123679151, 'min_data_in_leaf': 45}. Best is trial 33 with value: 0.0035648600275307203.


[LightGBM] [Warning] min_data_in_leaf is set=45, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=45
Mejores hiperparámetros: {'num_leaves': 990, 'subsample': 0.4913932898599116, 'colsample_bytree': 0.6988987393109299, 'min_data_in_leaf': 71}


### Random Forest

In [37]:
def objective(trial):
    # Definir los hiperparámetros a optimizar
    n_estimators = trial.suggest_int("n_estimators", 100, 500, step=50)
    max_depth = trial.suggest_int("max_depth", 10, 50, step=5)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    bootstrap = trial.suggest_categorical("bootstrap", [True, False])

    # Definir el modelo con los hiperparámetros actuales
    RF_model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        criterion="squared_error",
        random_state=0
    )

    # Entrenar el modelo
    RF_model.fit(X_train_scaled_df, y_train_scaled_df)

    # Predicciones en el conjunto de validación
    y_pred = RF_model.predict(X_val_scaled_df)
    rmse = mean_squared_error(y_val_scaled_df, y_pred)

    return rmse  # Optuna minimizará este valor

# Crear el estudio de optimización
RF_study = optuna.create_study(direction="minimize")
RF_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", RF_study.best_params)

[I 2025-03-14 15:12:59,842] A new study created in memory with name: no-name-bbc9b1da-c759-45f5-ab9d-0e52eea24dd1
[I 2025-03-14 15:13:01,491] Trial 0 finished with value: 0.0035382111655943896 and parameters: {'n_estimators': 200, 'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 0 with value: 0.0035382111655943896.
[I 2025-03-14 15:13:04,996] Trial 1 finished with value: 0.008150130135145709 and parameters: {'n_estimators': 250, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.0035382111655943896.
[I 2025-03-14 15:13:08,014] Trial 2 finished with value: 0.0036430905062935803 and parameters: {'n_estimators': 350, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.0035382111655943896.
[I 2025-03-14 15:13:10,081] Trial 3 finished with value: 0.003568261084719641 and parameters: {'n_estimators': 250, 'max_depth':

Mejores hiperparámetros: {'n_estimators': 100, 'max_depth': 30, 'min_samples_split': 16, 'min_samples_leaf': 7, 'bootstrap': True}


### CTNET

In [36]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])

    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

# Construir modelo con hiperparámetros sugeridos
def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout, mlp_dropout):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(x, x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)

    for units in mlp_units:
        x = layers.Dense(units, activation="relu")(x)

    x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(1)(x)
    return tf.keras.Model(inputs, outputs)

In [37]:
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [38]:
# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    head_size = trial.suggest_int("head_size", 2, 8)
    num_heads = trial.suggest_int("num_heads", 2, 8)
    ff_dim = trial.suggest_int("ff_dim", 16, 128, step=16)
    num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 5)
    mlp_units = [trial.suggest_int("mlp_units_1", 64, 512, step=64),
                 trial.suggest_int("mlp_units_2", 32, 256, step=32)]
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Construir el modelo
    model = build_model(
        input_shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]),
        head_size=head_size,
        num_heads=num_heads,
        ff_dim=ff_dim,
        num_transformer_blocks=num_transformer_blocks,
        mlp_units=mlp_units,
        dropout=dropout,
        mlp_dropout=mlp_dropout
    )

    # Compilar y entrenar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Minimizar MSE

# Crear el estudio de optimización
CTNET_study = optuna.create_study(direction="minimize")
CTNET_study.optimize(objective, n_trials=50)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", CTNET_study.best_params)


[I 2025-03-14 16:24:33,517] A new study created in memory with name: no-name-6c668fd9-2ad5-4259-b3c6-4f7e36a0d16d
[I 2025-03-14 16:26:03,151] Trial 0 finished with value: 0.08088389039039612 and parameters: {'head_size': 8, 'num_heads': 3, 'ff_dim': 112, 'num_transformer_blocks': 5, 'mlp_units_1': 320, 'mlp_units_2': 32, 'dropout': 0.37550865144773293, 'mlp_dropout': 0.3023382505391271, 'learning_rate': 5.2690503797113496e-05, 'batch_size': 128}. Best is trial 0 with value: 0.08088389039039612.
[I 2025-03-14 16:27:31,463] Trial 1 finished with value: 0.05246976763010025 and parameters: {'head_size': 2, 'num_heads': 4, 'ff_dim': 64, 'num_transformer_blocks': 5, 'mlp_units_1': 192, 'mlp_units_2': 128, 'dropout': 0.2024404970435556, 'mlp_dropout': 0.2708725767838099, 'learning_rate': 6.21478777195467e-05, 'batch_size': 256}. Best is trial 1 with value: 0.05246976763010025.
[I 2025-03-14 16:28:16,373] Trial 2 finished with value: 0.022172562777996063 and parameters: {'head_size': 4, 'num_h

Mejores hiperparámetros: {'head_size': 3, 'num_heads': 5, 'ff_dim': 128, 'num_transformer_blocks': 4, 'mlp_units_1': 64, 'mlp_units_2': 64, 'dropout': 0.24660642380724143, 'mlp_dropout': 0.14852584809648614, 'learning_rate': 0.0007986646130384079, 'batch_size': 256}


### Forescasting

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv1D, BatchNormalization, MaxPooling1D, Bidirectional, LSTM, Dropout, Dense
from tensorflow.keras.optimizers import Adam

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters = trial.suggest_categorical("filters", [32, 64, 128])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    lstm_units_1 = trial.suggest_categorical("lstm_units_1", [64, 128, 256])
    lstm_units_2 = trial.suggest_categorical("lstm_units_2", [32, 64, 128])
    lstm_units_3 = trial.suggest_categorical("lstm_units_3", [16, 32, 64])
    dropout_lstm = trial.suggest_float("dropout_lstm", 0.1, 0.5)
    dropout_dense = trial.suggest_float("dropout_dense", 0.1, 0.5)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])  # 🔹 Optimización del batch size

    # Construcción del modelo
    model = Sequential()
    model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

    # CNN
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, padding='same', activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(pool_size=2))

    # BiLSTM
    model.add(Bidirectional(LSTM(lstm_units_1, return_sequences=True)))
    model.add(Bidirectional(LSTM(lstm_units_2, return_sequences=True)))
    model.add(Dropout(dropout_lstm))
    model.add(Bidirectional(LSTM(lstm_units_3, return_sequences=False)))

    # Normalización y Dropout
    model.add(BatchNormalization())
    model.add(Dropout(dropout_dense))

    # Capas Densas
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Entrenar el modelo con validación
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se puede detener antes con Early Stopping
        batch_size=batch_size,  # 🔹 Batch size optimizado
        validation_data=(X_val_windowed, y_val_windowed),  # 🔹 Validación en cada época
        callbacks=[early_stop],  # 🔹 Early Stopping activado
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Forecasting_study = optuna.create_study(direction="minimize")
Forecasting_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Forecasting_study.best_params)

[I 2025-03-14 17:13:09,328] A new study created in memory with name: no-name-04f5ea84-658c-4690-b386-a7739f2bb562
[I 2025-03-14 17:14:29,654] Trial 9 finished with value: 0.13768203556537628 and parameters: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.10149417948428048, 'dropout_dense': 0.2538427010548123, 'learning_rate': 0.008672505066956365, 'batch_size': 256}. Best is trial 9 with value: 0.13768203556537628.
[I 2025-03-14 17:14:41,160] Trial 12 finished with value: 0.4284745454788208 and parameters: {'filters': 128, 'kernel_size': 2, 'lstm_units_1': 128, 'lstm_units_2': 64, 'lstm_units_3': 16, 'dropout_lstm': 0.38478086545173995, 'dropout_dense': 0.3055166479540916, 'learning_rate': 0.0016590994889786603, 'batch_size': 128}. Best is trial 9 with value: 0.13768203556537628.
[I 2025-03-14 17:14:52,568] Trial 13 finished with value: 0.3677898943424225 and parameters: {'filters': 32, 'kernel_size': 5, 'lstm_units_1': 6

Mejores hiperparámetros: {'filters': 64, 'kernel_size': 2, 'lstm_units_1': 256, 'lstm_units_2': 64, 'lstm_units_3': 64, 'dropout_lstm': 0.31196916627553595, 'dropout_dense': 0.49436107395722206, 'learning_rate': 0.00881680867870464, 'batch_size': 128}


### Photovoltaic

In [40]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Bidirectional, GRU, MultiHeadAttention
from tensorflow.keras.layers import Flatten, Dropout, Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import mean_squared_error

# Definir la función objetivo para Optuna
def objective(trial):
    # Hiperparámetros a optimizar
    filters_1 = trial.suggest_categorical("filters_1", [32, 64, 128])
    filters_2 = trial.suggest_categorical("filters_2", [64, 128, 256])
    kernel_size = trial.suggest_int("kernel_size", 2, 5)
    gru_units = trial.suggest_categorical("gru_units", [32, 64, 128])
    num_heads = trial.suggest_categorical("num_heads", [2, 4, 8])
    dropout_rate = trial.suggest_float("dropout_rate", 0.2, 0.5)
    dense_units_1 = trial.suggest_categorical("dense_units_1", [32, 64, 128])
    dense_units_2 = trial.suggest_categorical("dense_units_2", [16, 32, 64])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)
    batch_size = trial.suggest_categorical("batch_size", [128, 256, 512])

    # Definir el modelo
    inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

    # Primera capa CNN
    x = Conv1D(filters=filters_1, kernel_size=kernel_size, padding='same', activation='relu')(inputs)
    x = MaxPooling1D(pool_size=2)(x)

    # Segunda capa CNN
    x = Conv1D(filters=filters_2, kernel_size=kernel_size, padding='same', activation='relu')(x)
    x = MaxPooling1D(pool_size=2)(x)

    # Capa BiGRU
    x = Bidirectional(GRU(gru_units, return_sequences=True))(x)

    # Atención MultiHead
    attention = MultiHeadAttention(num_heads=num_heads, key_dim=128)(x, x)

    # Aplanar y Dropout
    x = Flatten()(attention)
    x = Dropout(dropout_rate)(x)
    x = Dense(dense_units_1, activation="relu", kernel_regularizer=l2(0.01))(x)
    x = Dense(dense_units_2, activation="relu")(x)

    # Capa de salida
    outputs = Dense(1, activation="linear")(x)

    # Construcción del modelo
    model = Model(inputs=inputs, outputs=outputs)

    # Compilar el modelo
    model.compile(
        loss=tf.keras.losses.MeanSquaredError(),
        optimizer=Adam(learning_rate=learning_rate),
        metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

    # Early Stopping
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)

    # Entrenar el modelo
    history = model.fit(
        X_train_windowed, y_train_windowed,
        epochs=100,  # Se detendrá con Early Stopping
        batch_size=batch_size,
        validation_data=(X_val_windowed, y_val_windowed),
        callbacks=[early_stop],
        verbose=0
    )

    # Obtener la mejor pérdida de validación
    val_loss = min(history.history['val_loss'])
    return val_loss  # Optuna minimizará este valor

# Crear el estudio de optimización
Photovoltaic_study = optuna.create_study(direction="minimize")
Photovoltaic_study.optimize(objective, n_trials=50, n_jobs=-1)  # Ejecutar 50 pruebas

# Imprimir los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", Photovoltaic_study.best_params)

[I 2025-03-14 17:21:29,963] A new study created in memory with name: no-name-febddb7c-399b-4023-a151-185972d7fb78


Epoch 67: early stopping
Restoring model weights from the end of the best epoch: 57.


[I 2025-03-14 17:23:11,946] Trial 8 finished with value: 0.016582762822508812 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.30214995808846173, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.001536761055530737, 'batch_size': 512}. Best is trial 8 with value: 0.016582762822508812.


Epoch 57: early stopping
Restoring model weights from the end of the best epoch: 47.


[I 2025-03-14 17:23:35,047] Trial 10 finished with value: 0.02955016680061817 and parameters: {'filters_1': 32, 'filters_2': 64, 'kernel_size': 5, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.2563503794673836, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.0069657106221652654, 'batch_size': 256}. Best is trial 8 with value: 0.016582762822508812.


Epoch 58: early stopping
Restoring model weights from the end of the best epoch: 48.


[I 2025-03-14 17:23:38,941] Trial 3 finished with value: 0.016966640949249268 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 4, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.4854765047673599, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0014674446479185732, 'batch_size': 256}. Best is trial 8 with value: 0.016582762822508812.


Restoring model weights from the end of the best epoch: 100.


[I 2025-03-14 17:23:39,159] Trial 6 finished with value: 0.03173309937119484 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 5, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.348105527822375, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.0002224144851472268, 'batch_size': 512}. Best is trial 8 with value: 0.016582762822508812.


Restoring model weights from the end of the best epoch: 100.


[I 2025-03-14 17:23:40,323] Trial 7 finished with value: 0.026846325024962425 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.22284802478767524, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.00019246894401031504, 'batch_size': 512}. Best is trial 8 with value: 0.016582762822508812.


Epoch 73: early stopping
Restoring model weights from the end of the best epoch: 63.


[I 2025-03-14 17:24:04,692] Trial 2 finished with value: 0.01968076080083847 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 2, 'dropout_rate': 0.4072306643630518, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0002563449678724417, 'batch_size': 256}. Best is trial 8 with value: 0.016582762822508812.


Epoch 50: early stopping
Restoring model weights from the end of the best epoch: 40.


[I 2025-03-14 17:24:28,553] Trial 4 finished with value: 0.017776770517230034 and parameters: {'filters_1': 32, 'filters_2': 128, 'kernel_size': 4, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.31684928864698714, 'dense_units_1': 64, 'dense_units_2': 16, 'learning_rate': 0.000747266537010153, 'batch_size': 128}. Best is trial 8 with value: 0.016582762822508812.


Restoring model weights from the end of the best epoch: 100.


[I 2025-03-14 17:24:44,457] Trial 0 finished with value: 0.055394869297742844 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.38211939455796196, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.00414355643550462, 'batch_size': 256}. Best is trial 8 with value: 0.016582762822508812.


Restoring model weights from the end of the best epoch: 100.


[I 2025-03-14 17:24:44,713] Trial 1 finished with value: 0.2016880214214325 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.3884862716563018, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.008791207227080973, 'batch_size': 256}. Best is trial 8 with value: 0.016582762822508812.


Epoch 90: early stopping
Restoring model weights from the end of the best epoch: 80.


[I 2025-03-14 17:24:47,500] Trial 12 finished with value: 0.12571613490581512 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 5, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.3814746108962358, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.009233563846842058, 'batch_size': 512}. Best is trial 8 with value: 0.016582762822508812.


Epoch 60: early stopping
Restoring model weights from the end of the best epoch: 50.


[I 2025-03-14 17:24:53,503] Trial 5 finished with value: 0.017588792368769646 and parameters: {'filters_1': 32, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 32, 'num_heads': 8, 'dropout_rate': 0.267432141400711, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0015818943476571502, 'batch_size': 128}. Best is trial 8 with value: 0.016582762822508812.


Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 51.


[I 2025-03-14 17:24:56,385] Trial 9 finished with value: 0.016580283641815186 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4372078086487314, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0002695591002455885, 'batch_size': 128}. Best is trial 9 with value: 0.016580283641815186.


Epoch 71: early stopping
Restoring model weights from the end of the best epoch: 61.


[I 2025-03-14 17:25:10,391] Trial 16 finished with value: 0.018993545323610306 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2802799147741889, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.0006317476833036154, 'batch_size': 512}. Best is trial 9 with value: 0.016580283641815186.


Epoch 59: early stopping
Restoring model weights from the end of the best epoch: 49.


[I 2025-03-14 17:25:19,302] Trial 13 finished with value: 0.019467880949378014 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.20802959257644238, 'dense_units_1': 32, 'dense_units_2': 16, 'learning_rate': 0.00036654347913543347, 'batch_size': 256}. Best is trial 9 with value: 0.016580283641815186.


Restoring model weights from the end of the best epoch: 97.


[I 2025-03-14 17:25:45,560] Trial 17 finished with value: 0.020096058025956154 and parameters: {'filters_1': 32, 'filters_2': 256, 'kernel_size': 4, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.2534239225699626, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0003713137373897494, 'batch_size': 512}. Best is trial 9 with value: 0.016580283641815186.


Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.


[I 2025-03-14 17:25:53,076] Trial 15 finished with value: 0.0175652876496315 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 5, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.3090219812806848, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0008477012659747494, 'batch_size': 128}. Best is trial 9 with value: 0.016580283641815186.


Epoch 43: early stopping
Restoring model weights from the end of the best epoch: 33.


[I 2025-03-14 17:25:55,049] Trial 14 finished with value: 0.01767631061375141 and parameters: {'filters_1': 64, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 8, 'dropout_rate': 0.445647144563712, 'dense_units_1': 128, 'dense_units_2': 32, 'learning_rate': 0.002210837280385628, 'batch_size': 128}. Best is trial 9 with value: 0.016580283641815186.


Epoch 86: early stopping
Restoring model weights from the end of the best epoch: 76.


[I 2025-03-14 17:26:04,186] Trial 11 finished with value: 0.016573505476117134 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.47509134960706595, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00015504366983383065, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 51.


[I 2025-03-14 17:26:05,942] Trial 22 finished with value: 0.01778654381632805 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.49019136134247787, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0014202922990082974, 'batch_size': 512}. Best is trial 11 with value: 0.016573505476117134.


Epoch 76: early stopping
Restoring model weights from the end of the best epoch: 66.


[I 2025-03-14 17:26:10,531] Trial 19 finished with value: 0.016636347398161888 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 5, 'gru_units': 32, 'num_heads': 2, 'dropout_rate': 0.4552704483080931, 'dense_units_1': 32, 'dense_units_2': 64, 'learning_rate': 0.003939996627149614, 'batch_size': 512}. Best is trial 11 with value: 0.016573505476117134.


Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 30.


[I 2025-03-14 17:26:44,501] Trial 20 finished with value: 0.018277134746313095 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.44544854117359806, 'dense_units_1': 128, 'dense_units_2': 16, 'learning_rate': 0.0017054166135906585, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Epoch 44: early stopping
Restoring model weights from the end of the best epoch: 34.


[I 2025-03-14 17:27:03,367] Trial 21 finished with value: 0.01739422045648098 and parameters: {'filters_1': 64, 'filters_2': 64, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.2872801239890302, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.0015871785146502817, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.


[I 2025-03-14 17:27:03,689] Trial 23 finished with value: 0.017781218513846397 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.46750626186713534, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0005201264274341644, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Epoch 62: early stopping
Restoring model weights from the end of the best epoch: 52.


[I 2025-03-14 17:27:14,832] Trial 18 finished with value: 0.017798077315092087 and parameters: {'filters_1': 128, 'filters_2': 256, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 8, 'dropout_rate': 0.304729605071797, 'dense_units_1': 32, 'dense_units_2': 32, 'learning_rate': 0.0002807937690633105, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Epoch 82: early stopping
Restoring model weights from the end of the best epoch: 72.


[I 2025-03-14 17:29:42,712] Trial 27 finished with value: 0.017142897471785545 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.45852928862454256, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00010555852939879623, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Restoring model weights from the end of the best epoch: 97.


[I 2025-03-14 17:29:45,491] Trial 24 finished with value: 0.01705513894557953 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4632919633192835, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0001022468876576455, 'batch_size': 128}. Best is trial 11 with value: 0.016573505476117134.


Restoring model weights from the end of the best epoch: 97.


[I 2025-03-14 17:29:49,880] Trial 25 finished with value: 0.0158173069357872 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4684439880476973, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00012145096917937424, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 97.


[I 2025-03-14 17:30:11,271] Trial 26 finished with value: 0.016281353309750557 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.45520090043606665, 'dense_units_1': 128, 'dense_units_2': 64, 'learning_rate': 0.00010132278343422777, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 99.


[I 2025-03-14 17:30:33,432] Trial 28 finished with value: 0.016293473541736603 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.49989786060147934, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00011857896808060761, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 92.


[I 2025-03-14 17:30:41,331] Trial 30 finished with value: 0.017280766740441322 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.44221844638380897, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00010737796251395095, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 94.


[I 2025-03-14 17:30:49,560] Trial 29 finished with value: 0.016329597681760788 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.4891508106599153, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00013013215869548298, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 85: early stopping
Restoring model weights from the end of the best epoch: 75.


[I 2025-03-14 17:30:55,705] Trial 33 finished with value: 0.017697127535939217 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.41789955597590744, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.0001228934097951875, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 99.


[I 2025-03-14 17:30:57,988] Trial 31 finished with value: 0.016595840454101562 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.43202123913854856, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00010753770089742137, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 98.


[I 2025-03-14 17:31:11,496] Trial 32 finished with value: 0.01854044198989868 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.4198194932396995, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00011242754586903902, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 94.


[I 2025-03-14 17:31:37,508] Trial 34 finished with value: 0.01828690990805626 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.42065957557245975, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00011722191194559235, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 96.


[I 2025-03-14 17:31:51,832] Trial 35 finished with value: 0.01586611196398735 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.4259019639858379, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00010835942936753188, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 63: early stopping
Restoring model weights from the end of the best epoch: 53.


[I 2025-03-14 17:33:05,620] Trial 39 finished with value: 0.022935712710022926 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.4205351015653501, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00014227842139407778, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 46.


[I 2025-03-14 17:33:32,470] Trial 43 finished with value: 0.02108967863023281 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4998692692877168, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00015849906969286513, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 46.


[I 2025-03-14 17:33:37,214] Trial 44 finished with value: 0.024336274713277817 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4984584030128777, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00015199160611606375, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 88: early stopping
Restoring model weights from the end of the best epoch: 78.


[I 2025-03-14 17:33:48,303] Trial 38 finished with value: 0.0183050949126482 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 4, 'dropout_rate': 0.424706426248161, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00016381102910951586, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 76: early stopping
Restoring model weights from the end of the best epoch: 66.


[I 2025-03-14 17:34:05,563] Trial 41 finished with value: 0.018492842093110085 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.41941200455368216, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00015053235255814754, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 100.


[I 2025-03-14 17:34:10,010] Trial 36 finished with value: 0.01781564950942993 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.4151636081292728, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00011700406938348421, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 92.


[I 2025-03-14 17:34:12,462] Trial 47 finished with value: 0.020903097465634346 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4996658865610238, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00016817055611126789, 'batch_size': 256}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 95.


[I 2025-03-14 17:34:15,815] Trial 37 finished with value: 0.017737621441483498 and parameters: {'filters_1': 64, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 64, 'num_heads': 2, 'dropout_rate': 0.40967699273300295, 'dense_units_1': 64, 'dense_units_2': 32, 'learning_rate': 0.00015573297328417014, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 82: early stopping
Restoring model weights from the end of the best epoch: 72.


[I 2025-03-14 17:34:30,228] Trial 45 finished with value: 0.018405813723802567 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4965073251341755, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0001556887920653057, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 71: early stopping
Restoring model weights from the end of the best epoch: 61.


[I 2025-03-14 17:34:30,597] Trial 48 finished with value: 0.02150479517877102 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.3735902850178137, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0001868640284598941, 'batch_size': 256}. Best is trial 25 with value: 0.0158173069357872.


Epoch 74: early stopping
Restoring model weights from the end of the best epoch: 64.


[I 2025-03-14 17:34:32,844] Trial 46 finished with value: 0.01878054067492485 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4937626928214732, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00016576293116856106, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Epoch 93: early stopping
Restoring model weights from the end of the best epoch: 83.


[I 2025-03-14 17:34:32,905] Trial 42 finished with value: 0.01683156192302704 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.499325887490212, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.0001550254133331282, 'batch_size': 128}. Best is trial 25 with value: 0.0158173069357872.


Restoring model weights from the end of the best epoch: 91.


[I 2025-03-14 17:34:34,068] Trial 40 finished with value: 0.015087977051734924 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4207136145233795, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00014469265960224032, 'batch_size': 128}. Best is trial 40 with value: 0.015087977051734924.


Restoring model weights from the end of the best epoch: 91.


[I 2025-03-14 17:34:42,808] Trial 49 finished with value: 0.020243167877197266 and parameters: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 3, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.38840541337378737, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00018269631293757585, 'batch_size': 256}. Best is trial 40 with value: 0.015087977051734924.


Mejores hiperparámetros: {'filters_1': 128, 'filters_2': 128, 'kernel_size': 2, 'gru_units': 128, 'num_heads': 4, 'dropout_rate': 0.4207136145233795, 'dense_units_1': 64, 'dense_units_2': 64, 'learning_rate': 0.00014469265960224032, 'batch_size': 128}
